name: Build Windows EXE
on: [push]

jobs:
  build:  # <<< 2 espaços aqui
    runs-on: windows-latest
    steps:
      - name: Checkout code  # <<< 6 espaços (2 níveis)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --icon=icon.icns main.py  # <<< Corrigido "--icon-icon.ico"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Executable
          path: dist/main.exe